---
services:
  migrate:
    image: ghcr.io/bw8hook/totvs-rfp:test-docker
    container_name: migrate_totvs_rfp
    env_file: ".env"
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command: "php artisan migrate --force"


    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    image: ghcr.io/bw8hook/totvs-rfp:test-docker
    container_name: totvs_rfp
    ports:
      - "9001:9000"
      # - "443:443"
    env_file: ".env"
    depends_on:
      migrate:
        condition: service_completed_successfully

    extra_hosts:
      - "host.docker.internal:host-gateway"
