---
services:
  # migrate:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: migrate_totvs_rfp
  #   env_file: ".env"
  #   command: php artisan migrate --force

  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  app:
    image: ghcr.io/bw8hook/totvs-rfp:feature-add-docker
    container_name: totvs-rfp
    ports:
      - "8080:8080"
    env_file: ".env"
    #depends_on:
    #migrate:
    #condition: service_completed_successfully
